<a href="https://colab.research.google.com/github/Piyush1kgp/Deep-Lizard_Keras_tf/blob/master/Deeplizard_tf_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import  MinMaxScaler

In [2]:
train_lables = []
train_samples = []

We create our own random dataset with theme as: 1. 2100 patients went to clinical trail with age 13-100 out of which 95% with aged more than 65 yrs experienced side effects while 5% for aged less than 65. Out of total pool ot participants, half of total population is aged less than 65 yrs.

In [3]:
for i in range(50):
  #5% that experienced side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_lables.append(1)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_lables.append(0)

for i in range(1000):
  #5% that experienced side effects
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_lables.append(0)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_lables.append(1)
  

In [4]:
for i in train_samples:
  print(i)

14
96
22
98
57
88
42
96
59
79
56
94
19
77
62
93
34
72
18
90
23
90
47
96
39
81
13
71
55
86
37
96
55
69
21
91
30
83
44
83
47
67
49
91
16
99
52
88
37
76
62
86
15
73
28
83
31
71
28
78
50
68
30
89
28
88
28
69
54
92
26
78
22
78
27
74
41
76
43
95
17
73
33
83
21
90
52
91
23
99
64
85
61
68
40
94
15
80
63
82
26
94
20
99
64
87
16
84
46
99
22
81
45
75
37
97
49
69
36
70
45
80
57
70
38
71
30
79
43
94
24
71
41
75
44
92
52
74
61
99
48
71
59
95
25
100
54
90
58
100
22
68
62
100
45
68
43
76
35
70
13
70
22
76
35
97
21
66
44
84
51
85
33
97
56
87
18
66
33
99
52
90
62
68
22
77
30
65
57
75
16
71
57
95
47
85
27
71
54
81
34
97
17
90
32
75
42
92
20
66
61
75
53
86
47
71
59
78
20
73
56
91
42
76
57
86
44
73
60
87
36
86
30
93
38
83
37
90
33
69
13
85
28
95
18
77
32
86
32
76
19
79
40
94
56
83
34
71
38
80
63
82
14
84
63
80
33
72
44
93
19
92
35
88
52
98
55
81
22
67
48
81
35
76
30
92
61
96
29
83
38
82
54
78
49
88
21
68
59
87
36
75
14
100
46
100
53
75
43
88
60
84
23
76
23
75
33
92
55
95
47
83
44
92
34
94
40
79
54
78
27
67

In [5]:
for i in train_lables:
  print(i)

1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [6]:
#Now converting the list to numpy array
train_samples = np.array(train_samples)
train_lables = np.array(train_lables)
train_lables, train_samples = shuffle(train_lables, train_samples)

In [7]:
train_samples

array([50, 38, 75, ..., 61, 75, 22])

In [8]:
train_samples.reshape(-1,1) #used to convert 1-d to 2-d array so that it can be used by function for transformation

array([[50],
       [38],
       [75],
       ...,
       [61],
       [75],
       [22]])

In [9]:
scaler = MinMaxScaler()
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [10]:
scaled_train_samples

array([[0.42528736],
       [0.28735632],
       [0.71264368],
       ...,
       [0.55172414],
       [0.71264368],
       [0.10344828]])

Now utilising the Keras API

In [11]:
import tensorflow as tf

In [12]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
#Above ones will be used while we build our model and lower ones while we train the model
from tensorflow.keras.optimizers import Adam 
from tensorflow.keras.metrics import categorical_crossentropy

In [13]:
#To check whether tf has identifies the GPU and as well as enable memory growth
physical_devices = tf.config.experimental.list_physical_devices('GPU')
print("Num GPUs available",  len(physical_devices))
tf.config.experimental.set_memory_growth(physical_devices[0],True)

Num GPUs available 1


In [14]:
#let's build a Sequential model which can be defined as linear stack of layers
model = Sequential([
                    Dense(units = 16, input_shape=(1,), activation = 'relu'),
                    Dense(units = 32, activation = 'relu'),
                    Dense(units = 2, activation = 'softmax')
])

In [15]:
"""for the dense layer with 16 units: first hidden/ second layer including first as input layer. Units are also called nodes/neurons
for the dense layer with 2 units: it depicts it as final layer or output layer. 2 units corresponds to the possibility of 2 output classes
"""

'for the dense layer with 16 units: first hidden/ second layer including first as input layer. Units are also called nodes/neurons\nfor the dense layer with 2 units: it depicts it as final layer or output layer. 2 units corresponds to the possibility of 2 output classes\n'

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics =['accuracy']) # This prepares the model for training

In [18]:
#model.fit(x = scaled_train_samples, y = train_lables, batch_size=15, epochs=29, verbose=2, shuffle= True)

In [19]:
model.fit(x = scaled_train_samples, y = train_lables, validation_split = 0.1, batch_size=10, epochs=30, verbose=2, shuffle= True)
# This function helps to get a separate set of validation set that can be used to identify how general our model is
# We need data to be shuffled before applying the validation split, using the above function with shuffle = True , it will be executed before validation_split
# Hence, here the shuffle we made in starting codes proved to be helpful

Epoch 1/30
189/189 - 1s - loss: 0.7099 - accuracy: 0.4921 - val_loss: 0.6926 - val_accuracy: 0.4905
Epoch 2/30
189/189 - 0s - loss: 0.6745 - accuracy: 0.6905 - val_loss: 0.6544 - val_accuracy: 0.7857
Epoch 3/30
189/189 - 0s - loss: 0.6421 - accuracy: 0.7693 - val_loss: 0.6224 - val_accuracy: 0.8048
Epoch 4/30
189/189 - 0s - loss: 0.6140 - accuracy: 0.7725 - val_loss: 0.5927 - val_accuracy: 0.8143
Epoch 5/30
189/189 - 0s - loss: 0.5869 - accuracy: 0.7905 - val_loss: 0.5639 - val_accuracy: 0.8190
Epoch 6/30
189/189 - 0s - loss: 0.5596 - accuracy: 0.8111 - val_loss: 0.5355 - val_accuracy: 0.8333
Epoch 7/30
189/189 - 0s - loss: 0.5324 - accuracy: 0.8201 - val_loss: 0.5074 - val_accuracy: 0.8524
Epoch 8/30
189/189 - 0s - loss: 0.5049 - accuracy: 0.8402 - val_loss: 0.4782 - val_accuracy: 0.8571
Epoch 9/30
189/189 - 0s - loss: 0.4777 - accuracy: 0.8513 - val_loss: 0.4521 - val_accuracy: 0.8762
Epoch 10/30
189/189 - 0s - loss: 0.4526 - accuracy: 0.8635 - val_loss: 0.4274 - val_accuracy: 0.8857

In [20]:
# Hence, our model is generalizing pretty well and it's not overfitting the training dataset

In [21]:
# Prepare the Test set followed by testing the model 

In [22]:
test_lables = []
test_samples = []

In [23]:
for i in range(5):
  #5% that experienced side effects
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_lables.append(1)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_lables.append(0)

for i in range(100):
  #5% that experienced side effects
  random_younger = randint(13,64)
  test_samples.append(random_younger)
  test_lables.append(0)

  random_older = randint(65,100)
  test_samples.append(random_older)
  test_lables.append(1)


In [24]:
test_lables = np.array(test_lables)
test_samples = np.array(test_samples)
test_lables, test_samples = shuffle(test_lables, test_samples)

In [25]:
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [26]:
#Predicting the model accuracy

In [27]:
predictions = model.predict(x = scaled_test_samples, batch_size= 10, verbose=0) #verbose = 0, when we don't need any output from the given function. this is used to how detailed we want the output 
#0, 1, or 2. Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch. Note that the progress bar is not particularly useful when logged to a file, so verbose=2 is recommended when not running interactively (eg, in a production environment).

In [28]:
for i in predictions:
  print(i)

[0.3476696  0.65233046]
[0.6885805  0.31141952]
[0.9512497  0.04875025]
[0.9533595  0.04664058]
[0.31894085 0.6810591 ]
[0.04129217 0.9587078 ]
[0.9544167  0.04558333]
[0.05261177 0.9473882 ]
[0.03449613 0.96550393]
[0.07609323 0.9239068 ]
[0.17730556 0.8226944 ]
[0.91258585 0.08741408]
[0.3476696  0.65233046]
[0.71561956 0.2843804 ]
[0.95455325 0.04544679]
[0.95468867 0.04531126]
[0.9533595  0.04664058]
[0.9507809  0.04921904]
[0.03057867 0.96942127]
[0.29152521 0.7084748 ]
[0.31894085 0.6810591 ]
[0.95461035 0.04538963]
[0.07110409 0.9288959 ]
[0.05939003 0.94061   ]
[0.07110409 0.9288959 ]
[0.9472396  0.05276037]
[0.9472396  0.05276037]
[0.95280504 0.04719502]
[0.954506   0.04549398]
[0.6601913 0.3398087]
[0.6306025  0.36939752]
[0.6306025  0.36939752]
[0.59999824 0.4000018 ]
[0.02881846 0.9711816 ]
[0.37755144 0.6224485 ]
[0.95469195 0.04530802]
[0.02881846 0.9711816 ]
[0.90170205 0.09829791]
[0.7876586 0.2123414]
[0.9507809  0.04921904]
[0.9493952  0.05060479]
[0.31894085 0.681059

In [29]:
#where 0th index tells about the probability of not having the side effect while 1st index tells about having it.

In [30]:
rounded_predictions = np.argmax(predictions, axis= 1)

In [31]:
rounded_predictions

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [32]:
#Confusion Matrix
%matplotlib inline
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

In [33]:
cm = confusion_matrix(y_true=test_lables, y_pred= rounded_predictions)

In [34]:
from sklearn.metrics import plot_confusion_matrix
# Plot non-normalized confusion matrix
plot_confusion_matrix(cm_plot_labels,test_lables, rounded_predictions)
plt.show()  

NameError: ignored

In [35]:
#Save & load a model 

In [36]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [38]:
! pip install h5py pyyaml

In [45]:
#check first is there any file exists with that specific address & then use model.save()
import os.path
#if os.path.isfile('drive/medical_trial_model.h5') is False:
model.save('medical_trial_model') #Will be saved in working directory

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: medical_trial_model/assets


Whole-model saving & loading
You can save an entire model to a single artifact. It will include:

The model's architecture/config
The model's weight values (which were learned during training)
The model's compilation information (if compile()) was called
The optimizer and its state, if any (this enables you to restart training where you left)


In [46]:
from tensorflow.keras.models import load_model
new_model = load_model('medical_trial_model')

In [47]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [48]:
new_model.get_weights()

[array([[ 0.46692622, -0.06386799,  0.12479585,  0.3136042 , -0.3720038 ,
         -0.23251909, -0.3993147 , -0.04750496, -0.30323318,  0.7196707 ,
          0.4251364 ,  0.46824676, -0.16663444, -0.46293905,  0.60741395,
          0.3405955 ]], dtype=float32),
 array([-0.14142428,  0.        ,  0.21863693, -0.10775186,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0154872 ,
        -0.13597931,  0.04884308,  0.        ,  0.        , -0.15397446,
        -0.10540733], dtype=float32),
 array([[-3.32357883e-01, -2.98058331e-01, -4.53449219e-01,
         -3.91554199e-02,  2.13452578e-01,  5.74082673e-01,
         -5.41110575e-01, -2.92212784e-01, -3.65979910e-01,
          5.69575429e-01,  6.14197180e-02,  4.89030242e-01,
         -2.71371424e-01, -1.80118605e-01,  4.52345818e-01,
          1.14086382e-01, -7.54702166e-02,  3.40740532e-01,
         -4.24069673e-01, -2.70601302e-01, -2.73040503e-01,
         -2.46813461e-01, -4.67420034e-02,  1.03244960e-01,
 

In [49]:
new_model.optimizer

Model to JSon format:
If we only need to save the architecture and not it's training configuration or weights.

In [51]:
json_string = model.to_json()
#in yaml format
yaml_string = model.to_yaml()

In [52]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_r

In [53]:
#model recontruction from JSON
from tensorflow.keras.models import model_from_json
model_architecture = model_from_json(json_string)

In [54]:
model_architecture.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [56]:
# Save only weights of model
model.save_weights('my_model_weights')

In [57]:
# if want to use the weights on another model, we need the same architecture
model2 = Sequential([
                    Dense(units = 16, input_shape=(1,), activation = 'relu'),
                    Dense(units = 32, activation = 'relu'),
                    Dense(units = 2, activation = 'softmax')
])

In [58]:
model2.load_weights('my_model_weights')

In [59]:
model2.get_weights()

[array([[ 0.46692622, -0.06386799,  0.12479585,  0.3136042 , -0.3720038 ,
         -0.23251909, -0.3993147 , -0.04750496, -0.30323318,  0.7196707 ,
          0.4251364 ,  0.46824676, -0.16663444, -0.46293905,  0.60741395,
          0.3405955 ]], dtype=float32),
 array([-0.14142428,  0.        ,  0.21863693, -0.10775186,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0154872 ,
        -0.13597931,  0.04884308,  0.        ,  0.        , -0.15397446,
        -0.10540733], dtype=float32),
 array([[-3.32357883e-01, -2.98058331e-01, -4.53449219e-01,
         -3.91554199e-02,  2.13452578e-01,  5.74082673e-01,
         -5.41110575e-01, -2.92212784e-01, -3.65979910e-01,
          5.69575429e-01,  6.14197180e-02,  4.89030242e-01,
         -2.71371424e-01, -1.80118605e-01,  4.52345818e-01,
          1.14086382e-01, -7.54702166e-02,  3.40740532e-01,
         -4.24069673e-01, -2.70601302e-01, -2.73040503e-01,
         -2.46813461e-01, -4.67420034e-02,  1.03244960e-01,
 